name: Build Godot Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Export Game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          export_debug: true
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-builds
          path: ${{ steps.export.outputs.archive_directory }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: build-${{ github.sha }}
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"
          TAG="build-${SHORT_SHA}"
          
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="Build ${SHORT_SHA}" \
            --notes="Automated build from commit ${GITHUB_SHA}" \
            ./artifacts/**/*
